### ISSUE TITLE
Không thấy nút tải sách 

### ISSUE THREAD

**Issue by thanhkhocnhe** [tiepvupsu/ebookML_src#1]
em đã nhận được mail của anh về tải sách,nhưng em vào trang  https://fundaml.com/ebook nhưng nó tự chuyển hướng về trang https://fundaml.com/dashboard và không thấy nút tải sách.mail của em là:15520814@gm.uit.edu.vn.em cũng đã dùng mail này đăng ký trên web https://fundaml.com/dashboard rồi

**Comment by daivuong7696** [comment]
Mình cũng gặp tình trạng tương tự, chắc phải đợi anh Tiệp fix rồi.

**Comment by thanhttvn** [comment]
Mình cũng không thấy nút tải sách mặc dù đã hoàn tất thanh toán và nhận được mail của anh để tải sách. Mail của mình: thanhtt_A05158@fpt.aptech.ac.vn

**Comment by TuanAnhPhanDepZai** [comment]
Anh xem giúp em với anh ơi. Em có mail la phantuananhlaanh@gmail.com

**Comment by daivuong7696** [comment]
Mấy bạn thử sử dụng firefox nhé, mình xài chrome không vào được nhưng firefox vào được.

**Comment by tiepvupsu** [comment]
Các bạn thử hard refresh hoặc sử dụng trình duyệt khác xem nhé.

**Comment by tiepvupsu** [comment]
Các bạn đăng ký nhưng chưa nhận được email chờ một chút nhé. Hệ thôngs đang nâng cấp.

**Comment by tiepvupsu** [comment]
Các bạn đã đăng ký đã được kích hoạt thành công rồi nhé. Không cần email xác nhận nữa.

**Comment by thanhttvn** [comment]
Chào anh tiệp e thử IE, Safari, firefox, chorme đều không thấy button tải sách, anh kiểm tra lại được không ạ.
Em cảm ơn anh.

**Comment by tiepvupsu** [comment]
Bạn thử force refresh (Shift+F5) trên windows xem sao.

**Comment by tiepvupsu** [comment]
Các bạn vào lại fundaml.com/ebook nhé, tôi đã fix lỗi không thấy nút 'Tải về'.
