### ISSUE TITLE
Tổng hợp 7/1

### ISSUE THREAD

**Issue by barcamania21** [tiepvupsu/ebookML_src#10]
Trang 184: "Đầu ra của sofmax network..."
Trang 186: "...vì nó là một vector ở dang one-het..."
                   "...Biểu thức này đạt giá trị ??? nhất nếu qc = 1..."
Trang 193: "...với các bài toán OR, AND, và OR..."
Trang 197: Hình 16.4, node cuối cùng của l_th layer, thiếu các chỉ số của z
Trang 215: "... Nhóm thứ hai, collaborative filtering, sẽ được thảo luận trong các chương còn lại của chương." (theo em nên để là "các chương còn lại của phần"
)
Trang 217: dòng đầu tiên: "được sản phẩm tới ngừời dùng..."
Trang 218 dòng cuối: "...đã được rated bởi ngừoi dùng thứ n..."
                                    "...(ở đây là số sao đã rate) của ngừoi dùng thứ n..."
(Em thấy lỗi này khá nhiều nhưng cũng chỉ lưu lại nhiêu đây :D)
Trang 219: "...sao cho mức độ quan tâm của một user tới một người dùng..."  (user quan tâm item ạ :D)
Hôm nay em mới đọc đến đây. Hẹn a ngày mai ạ :D

**Comment by tiepvupsu** [comment]
Cảm ơn em. Anh đọc lại thì Phần Hệ thống khuyến nghị bị lỗi rất nhiều. Anh đang sửa lại và sẽ cập nhật sớm.

**Comment by tiepvupsu** [comment]
Anh vừa cập nhật cả phần này rồi nhé.
