### ISSUE TITLE
Trang 143, 186

### ISSUE THREAD

**Issue by luongthanhlam** [tiepvupsu/ebookML_src#12]
Trang 143
* Hình 12.2 tương ứng với x 0 = −5
* Trong Hình 12.3 tương ứng với x 0 = 5

Trang 186
* Biểu thức này đạt giá trị nhất nếu q c = 1
* một vector ở dang one-het

Cái nữa là khi mình photo ebook thì số trang nằm ở mép trong khá khó tra cứu, một số ảnh minh họa không phân biệt được ( do in trắng đen )

**Comment by tiepvupsu** [comment]
Chào bạn. Mình chưa để ý đến chuyện in ra. Bản in chắc chắc sẽ khác và màu sắc sẽ được lưu ý. 

Các bạn sau in sách có thể in lệch một trang để số trang ở bên ngoài mép.

**Comment by tiepvupsu** [comment]
Hai lỗi ở Hình 12.2 và 12.3 đã được sửa.
