### ISSUE TITLE
1.2 Chuyển vị và Hermitian

### ISSUE THREAD

**Issue by ZuzooVn** [tiepvupsu/ebookML_src#16]
<img width="333" alt="screen shot 2018-01-18 at 10 34 23 pm" src="https://user-images.githubusercontent.com/1429230/35106043-c636d5b6-fc9f-11e7-975a-d89747b3bad4.png">

Chỗ này em nghĩ ```[x1 x2 .... x m]``` là  ```[x1 x2 .... x n] ```

**Comment by tiepvupsu** [comment]
fixed.
