### ISSUE TITLE
Đã refresh nhưng vẫn không thấy nút "Tải sách"

### ISSUE THREAD

**Issue by truong225** [tiepvupsu/ebookML_src#3]
Em đã thử trên mọi trình duyệt Opera, Edge, Chrome, Vivaldi, Firefox và thử Refresh như anh nói nhưng vẫn không thấy nút tải sách. Anh Tiệp có thể xử lý giúp em được không ạ?

**Comment by tiepvupsu** [comment]
Bạn email riêng cho mình nhé. Mình sẽ chỉ hướng giải quyết.
