### ISSUE TITLE
Sai subscript ở phương trình 1.15

### ISSUE THREAD

**Issue by dangngoctau** [tiepvupsu/ebookML_src#4]
Sách:
0 = x1a1 + x**1**a2 + · · · + xnan (1.15)
Nên:
0 = x1a1 + x**2**a2 + · · · + xnan (1.15)

**Comment by tiepvupsu** [comment]
Cảm ơn bạn, mình sẽ cập nhật sớm.

**Comment by tiepvupsu** [comment]
fixed.
